// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdaDCOcZFWzFnE6L0TctmUANOQjrbUDTc',
    appId: '1:1068463627227:web:461ea8fe0b71da662d25fe',
    messagingSenderId: '1068463627227',
    projectId: 'divina-advmobprog-ay2627',
    authDomain: 'divina-advmobprog-ay2627.firebaseapp.com',
    storageBucket: 'divina-advmobprog-ay2627.firebasestorage.app',
    measurementId: 'G-GSWLKZW9J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO0cf4LGkqJMfBmkTXVKJHOL0Tn09lsQY',
    appId: '1:1068463627227:android:747b76c521b0c5de2d25fe',
    messagingSenderId: '1068463627227',
    projectId: 'divina-advmobprog-ay2627',
    storageBucket: 'divina-advmobprog-ay2627.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2NW6iWI4ydLHPdF7wE7ps4CjaGHvWVYQ',
    appId: '1:1068463627227:ios:c497267e14a50e2f2d25fe',
    messagingSenderId: '1068463627227',
    projectId: 'divina-advmobprog-ay2627',
    storageBucket: 'divina-advmobprog-ay2627.firebasestorage.app',
    iosBundleId: 'com.example.divinaAdvmobprog',
  );
}
